export const getTransactions = async () => [
  {
    id: "123456789",
    note: "HyperCloud II Headset",
    category: "ACCESSORIES",
    createdAt: new Date("7/24/2022"),
    type: "EXPENSE",
    amount: 75,
    currency: "USD",
  },
  {
    id: "987546321",
    note: "Salary after promotion",
    category: "SALARY",
    createdAt: new Date("7/15/2022"),
    type: "INCOME",
    amount: 5_000_000,
    currency: "IQD",
  },
  {
    id: "987546322",
    note: "Borrowed from Muhammad",
    category: "LOAN",
    createdAt: new Date("1/10/2021"),
    type: "INCOME",
    amount: 100_000,
    currency: "IQD",
  },
  {
    id: "123",
    note: "HyperCloud II Headset",
    category: "ACCESSORIES",
    createdAt: new Date("7/24/2022"),
    type: "EXPENSE",
    amount: 75,
    currency: "USD",
  },
  {
    id: "456",
    note: "Salary after promotion",
    category: "SALARY",
    createdAt: new Date("7/15/2022"),
    type: "INCOME",
    amount: 5_000_000,
    currency: "IQD",
  },
  {
    id: "789",
    note: "Borrowed from Muhammad",
    category: "LOAN",
    createdAt: new Date("1/10/2021"),
    type: "INCOME",
    amount: 100_000,
    currency: "IQD",
  },
  {
    id: "321",
    note: "HyperCloud II Headset",
    category: "ACCESSORIES",
    createdAt: new Date("7/24/2022"),
    type: "EXPENSE",
    amount: 75,
    currency: "USD",
  },
  {
    id: "654",
    note: "Salary after promotion",
    category: "SALARY",
    createdAt: new Date("7/15/2022"),
    type: "INCOME",
    amount: 5_000_000,
    currency: "IQD",
  },
  {
    id: "987",
    note: "Borrowed from Muhammad",
    category: "LOAN",
    createdAt: new Date("1/10/2021"),
    type: "INCOME",
    amount: 100_000,
    currency: "IQD",
  },
  {
    id: "1234",
    note: "HyperCloud II Headset",
    category: "ACCESSORIES",
    createdAt: new Date("7/24/2022"),
    type: "EXPENSE",
    amount: 75,
    currency: "USD",
  },
  {
    id: "5678",
    note: "Salary after promotion",
    category: "SALARY",
    createdAt: new Date("7/15/2022"),
    type: "INCOME",
    amount: 5_000_000,
    currency: "IQD",
  },
  {
    id: "87564",
    note: "Borrowed from Muhammad",
    category: "LOAN",
    createdAt: new Date("1/10/2021"),
    type: "INCOME",
    amount: 100_000,
    currency: "IQD",
  },
];
